# Generated by Django 3.2.3 on 2021-05-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
                ('tech', models.CharField(max_length=100)),
            ],
        ),
    ]
